server:
  port: 3001

spring:
  profiles:
    active: dev
  web:
    resources:
      cache:
        period: 0

# logging:
#   level:
#     org.hibernate.SQL: WARN
#     org.hibernate.type: WARN
#     com.zaxxer.hikari: WARN
#     avr.crypto: INFO
#     avr.repository: WARN
#     avr.service.DynamicSchedulingService: WARN
#     org.springframework.jdbc.core: WARN
#     org.springframework.jdbc.core.JdbcTemplate: WARN
#     org.springframework.jdbc.core.StatementCreatorUtils: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    export:
      prometheus:
        enabled: true

encryption:
  master-key: masterOfPuppets
