server:
  port: 3001
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: tomcat

spring:
  profiles:
    active: dev
  web:
    resources:
      cache:
        period: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    export:
      prometheus:
        enabled: true

encryption:
  master-key: masterOfPuppets
